name: Create and publish a Docker images

on:
  push:
    tags:
      - 'v*'
env:
  REGISTRY: ghcr.io

jobs:
  build-converter:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        target: [converter,proxy]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and push
        uses: ./.github/actions/build
        with:
          artifact: ${{ matrix.target }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          dockefile: ./Dockerfile.${{ matrix.target }}
